### ISSUE TITLE
Difficulty getting program to generate random numbers

### ISSUE THREAD

**Issue by rdev5** [robseward/arduino-rng#1]
This is probably going to sound pretty vague starting off, but I can't seem to get the sketch to output numbers with `VON_NEUMANN` bias removal. It just seems to print a bunch of 0's, and a couple 9's every now and then.

I'm pretty much running your code as-is, along with the same circuit built on a Radio Shack PCB board. I can verify that the circuit is producing noise by hooking up a piezo buzzer to it and am also feeding it 11.5-12v.

I noticed back when the circuit was still on the breadboard that it would generate some random numbers if I tapped on certain components (probably causing a differential), but it just seems to be a steady stream of 0's for the most part.

Any input would be great. Thanks!

Also, as an aside, could you perhaps elaborate on why the following wouldn't suffice for collecting random numbers from the noise circuit? It's overly simple, I know, but it at least is generating all kinds of numbers. Admittedly, I'm not thoroughly versed on producing truly random numbers (though I realize the need for bias removal).

```
void loop() {
    byte n = analogRead(adc_pin) % 255;
    Serial.println(n);
}
```

**Comment by robseward** [comment]
Hi Matt, sorry for the delayed reply. I'm not sure why you're not getting a
signal. The most common mistake is not having a 12v supply.

The code you have written would create an uneven distribution of digits,
with the mean of the noise signal occurring the more frequently than other
digits, and hardly ever seeing a 0 or 255 value. As a random source, you
want your bytes to be evenly distributed between 0 and 255. That's we turn
it into a succession of random coin-flips – each 0 and 1 will get strung
together to create a random byte.

Hope this helps,
Rob

**Comment by rdev5** [comment]
That makes sense. It might be helpful from an academic standpoint to have a little more inline comments as I get the general idea of unbiasing but am still somewhat unfamiliar with the specific details of _properly implementing_ these algorithms.

**Comment by robseward** [comment]
To get high-quality randomness, you need a entropy extractor. As far as I know all hardware random number generators generate raw output that is imperfect, even if the algorithms are selected well. It's how you process the raw output that really makes a difference. Von Neumann bias removal is one method, but it is usually preferred to use a hash function such as AES-CBC-MAC. This discussion raises some good points: http://crypto.stackexchange.com/questions/10517/extracting-only-the-entropy
