### ISSUE TITLE
How to use it-program

### ISSUE THREAD

**Issue by juliamoranchomarzal** [robseward/arduino-rng#2]
i have bought the materials and made it but i don't know how to use it could you help me please

**Comment by rdev5** [comment]
I put together a circuit board myself based on this project as well. Mine uses an ATTiny85, however, and outputs the numbers to a series of LEDs in binary fashion to save on pins (i.e. mod 10 + shift register). I'm told my code still needs biasing, though I haven't been able to get this project's implementation of it to work; the running program and LED output is still fun to watch :)

Video: [My RNG2 Circuit on ATTiny85](https://goo.gl/photos/ZRDE54FfZQNx7bFo6)

Notes:
The red LED represents 0, by the way. Kind of hard to represent 0 which would look the same as the pause between numbers.

Also, you may notice I have a 2-pin header (port) at the top-right. That's a direct line into the noise generator if you wanted to hook up an external analog reader, etc.

The whole thing is powered by a 12V AC adapter but can also accept a 24V supply as there is a 12V regulator right next to the DC jack. There is a selector pin (yellow tab) which allows you to switch to using the 12V regulator if using > 12V supply, or bypass it altogether if using 12V directly.

The regulator just to the left of that is a 5V regulator for the ATTiny85 which you see in the middle of the board, which uses the shift register just above it to light up the LEDs up top while still having a pin free to read the signals from the noise circuit.

Needless to say, it was a lot of fun, and even relaxing, designing and putting it all together. Hope you have as much fun doing yours!
